Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"

  config.vm.box_check_update = false

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true

    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
    ./dotnet-install.ps1 -Version 6.0.416 -InstallDir "C:\\Program Files\\dotnet"
    rm ./dotnet-install.ps1
    $env:Path = $env:Path + ";C:\\Program Files\\dotnet"
    dotnet tool install --global --version 1.0.0 --add-source http://192.168.0.104:5000/v3/index.json --no-cache nkozlenko
  SHELL

end