Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false

     vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apt-transport-https

    sudo apt update
    sudo apt install -y apt-transport-https wget curl
    wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    sudo apt update
    sudo apt install -y dotnet-sdk-6.0

    su - vagrant -c "dotnet tool install --global --version 1.0.0 --add-source http://192.168.0.104:5000/v3/index.json --no-cache nkozlenko"
   SHELL
end

